name: readwhere_opds
description: OPDS catalog provider for ReadWhere
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.8.0

dependencies:
  readwhere_plugin:
    path: ../readwhere_plugin
  http: ^1.2.0
  xml: ^6.5.0
  collection: ^1.18.0
  equatable: ^2.0.5
  path: ^1.9.0

dev_dependencies:
  test: ^1.25.0
  mockito: ^5.4.0
  build_runner: ^2.4.0
