name: readwhere_kavita_plugin
description: Kavita server plugin for ReadWhere using unified plugin architecture
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.8.0

dependencies:
  readwhere_kavita:
    path: ../readwhere_kavita
  readwhere_opds:
    path: ../readwhere_opds
  readwhere_plugin:
    path: ../readwhere_plugin
  http: ^1.2.0
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  build_runner: ^2.4.0
