name: readwhere_cbr_plugin
description: CBR (Comic Book RAR) reader plugin implementation for ReadWhere.
version: 0.1.0
repository: https://github.com/cedricziel/readwhere
publish_to: none

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  readwhere_plugin:
    path: ../readwhere_plugin
  readwhere_cbr:
    path: ../readwhere_cbr
  readwhere_panel_detection:
    path: ../readwhere_panel_detection
  logging: ^1.3.0
  path: ^1.9.1
  image: ^4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.6.1
  build_runner: ^2.10.4
